In [ ]:
import os
import sys
import joblib
import logging
import numpy as np
import pandas as pd
import rasterio
import lightgbm as lgb

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

In [ ]:
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
    force=True
)

logging.info("Logging is working ✅")

In [ ]:
BASE_DIR = "/content/drive/MyDrive/PhytoLB"

GBIF_PATH = f"{BASE_DIR}/dwca-tree_lebanon-v1.0/occurrence.txt"
CLIMATE_DIR = f"{BASE_DIR}/wc2.1_10m_bio"
ELEVATION_PATH = f"{BASE_DIR}/elevation/elevation.tif"

SAVE_DIR = f"{BASE_DIR}/model_enhanced_v4"
os.makedirs(SAVE_DIR, exist_ok=True)

logging.info(f"Saving outputs to: {SAVE_DIR}")

In [ ]:
def load_gbif_txt(path):
    df = pd.read_csv(path, sep="\t", low_memory=False)

    if "species" not in df.columns:
        df["species"] = df["scientificName"]

    df = df[["species", "decimalLatitude", "decimalLongitude"]]
    df = df.dropna()

    df.columns = ["species", "lat", "lon"]

    df["lat"] = pd.to_numeric(df["lat"], errors="coerce")
    df["lon"] = pd.to_numeric(df["lon"], errors="coerce")
    df = df.dropna()

    # Lebanon bounding box
    df = df[
        (df["lat"] >= 33.0) & (df["lat"] <= 34.8) &
        (df["lon"] >= 35.0) & (df["lon"] <= 36.8)
    ]

    df = df.drop_duplicates()

    logging.info(f"GBIF loaded: {len(df)} records")
    logging.info(f"Unique species: {df['species'].nunique()}")

    return df

In [ ]:
class EnvironmentalExtractor:
    def __init__(self, climate_folder, elevation_path):
        self.climate_rasters = []

        for i in range(1, 20):
            path = os.path.join(climate_folder, f"wc2.1_10m_bio_{i}.tif")

            if not os.path.exists(path):
                raise FileNotFoundError(f"Missing climate file: {path}")

            self.climate_rasters.append(rasterio.open(path))

        if not os.path.exists(elevation_path):
            raise FileNotFoundError(f"Missing elevation file: {elevation_path}")

        self.elevation_raster = rasterio.open(elevation_path)

        logging.info("Climate + elevation rasters loaded ✅")

    def extract_point(self, lat, lon):
        values = []

        for raster in self.climate_rasters:
            try:
                val = next(raster.sample([(lon, lat)]))[0]

                if raster.nodata is not None and val == raster.nodata:
                    val = np.nan

            except Exception:
                val = np.nan

            values.append(val)

        try:
            elev = next(self.elevation_raster.sample([(lon, lat)]))[0]

            if self.elevation_raster.nodata is not None and elev == self.elevation_raster.nodata:
                elev = np.nan

        except Exception:
            elev = np.nan

        values.append(elev)

        return values

    def extract_dataframe(self, df):
        features = []
        total = len(df)

        for i, row in enumerate(df.itertuples(index=False)):
            values = self.extract_point(row.lat, row.lon)
            features.append(values)

            if i % 1000 == 0:
                logging.info(f"Processed {i}/{total} points")

        columns = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

        return pd.DataFrame(features, columns=columns)

In [ ]:
def generate_pseudo_absence(df, n_samples, extractor, random_state=42):
    np.random.seed(random_state)

    lat_min, lat_max = df["lat"].min(), df["lat"].max()
    lon_min, lon_max = df["lon"].min(), df["lon"].max()

    pseudo_rows = []
    attempts = 0
    max_attempts = n_samples * 10

    logging.info("Generating filtered pseudo-absence points...")

    while len(pseudo_rows) < n_samples and attempts < max_attempts:
        attempts += 1

        lat = np.random.uniform(lat_min, lat_max)
        lon = np.random.uniform(lon_min, lon_max)

        # Extract environmental values immediately
        values = extractor.extract_point(lat, lon)

        # Reject points with too many missing values
        if np.isnan(values).sum() > 2:
            continue

        # Reject invalid elevation values
        elevation = values[-1]

        if np.isnan(elevation):
            continue

        if elevation < -10 or elevation > 3200:
            continue

        species = df["species"].sample(1, random_state=np.random.randint(0, 999999)).iloc[0]

        row = {
            "species": species,
            "lat": lat,
            "lon": lon,
            "label": 0
        }

        pseudo_rows.append(row)

        if len(pseudo_rows) % 1000 == 0:
            logging.info(f"Generated {len(pseudo_rows)}/{n_samples} valid pseudo-absences")

    pseudo_df = pd.DataFrame(pseudo_rows)

    if len(pseudo_df) < n_samples:
        logging.warning(
            f"Only generated {len(pseudo_df)} pseudo-absences out of {n_samples}"
        )

    return pseudo_df

In [ ]:
def add_engineered_features(df):
    df = df.copy()

    # Temperature range / seasonality signals
    df["temp_annual_range"] = df["BIO5"] - df["BIO6"]
    df["warm_cold_quarter_diff"] = df["BIO10"] - df["BIO11"]

    # Precipitation seasonality signals
    df["precip_wet_dry_month_diff"] = df["BIO13"] - df["BIO14"]
    df["precip_wet_dry_quarter_diff"] = df["BIO16"] - df["BIO17"]

    # Ratios with safe division
    df["dryness_ratio"] = df["BIO17"] / (df["BIO16"] + 1e-6)
    df["summer_winter_precip_ratio"] = df["BIO18"] / (df["BIO19"] + 1e-6)

    # Elevation-climate interactions
    df["elevation_temp_interaction"] = df["elevation"] * df["BIO1"]
    df["elevation_precip_interaction"] = df["elevation"] * df["BIO12"]

    return df

In [ ]:
def build_dataset(df, extractor):
    logging.info("Extracting presence features...")

    presence_features = extractor.extract_dataframe(df)
    presence_features["species"] = df["species"].values
    presence_features["label"] = 1

    pseudo_df = generate_pseudo_absence(
        df=df,
        n_samples=len(df),
        extractor=extractor,
        random_state=42
    )

    logging.info("Extracting pseudo-absence features...")

    absence_features = extractor.extract_dataframe(pseudo_df)
    absence_features["species"] = pseudo_df["species"].values
    absence_features["label"] = 0

    full_df = pd.concat(
        [presence_features, absence_features],
        ignore_index=True
    )

    logging.info(f"Dataset before filtering: {full_df.shape}")

    # Remove rows where many environmental features are missing
    env_cols = [col for col in full_df.columns if col.startswith("BIO")] + ["elevation"]
    full_df["missing_count"] = full_df[env_cols].isna().sum(axis=1)

    full_df = full_df[full_df["missing_count"] <= 2]
    full_df = full_df.drop(columns=["missing_count"])

    logging.info(f"Dataset after filtering: {full_df.shape}")

    full_df = add_engineered_features(full_df)

    return full_df

In [ ]:
def get_model():
    return lgb.LGBMClassifier(
        objective="binary",
        n_estimators=900,
        learning_rate=0.02,
        max_depth=9,
        num_leaves=80,
        min_child_samples=15,
        subsample=0.9,
        subsample_freq=1,
        colsample_bytree=0.9,
        reg_alpha=0.05,
        reg_lambda=0.3,
        random_state=42,
        force_row_wise=True,
        verbose=-1
    )

In [ ]:

gbif = load_gbif_txt(GBIF_PATH)
gbif.to_csv(f"{SAVE_DIR}/clean_gbif.csv", index=False)


extractor = EnvironmentalExtractor(
    climate_folder=CLIMATE_DIR,
    elevation_path=ELEVATION_PATH
)

dataset = build_dataset(gbif, extractor)

logging.info(f"Final dataset shape: {dataset.shape}")
logging.info(f"Class distribution:\n{dataset['label'].value_counts()}")
logging.info(f"Missing values:\n{dataset.isna().sum().sort_values(ascending=False).head(10)}")

dataset.to_csv(f"{SAVE_DIR}/final_phyto_dataset.csv", index=False)
dataset.to_parquet(f"{SAVE_DIR}/final_phyto_dataset.parquet", index=False)

logging.info("Final dataset saved ✅")


X = dataset.drop(columns=["label"])
y = dataset["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

logging.info(f"Train size: {X_train.shape}")
logging.info(f"Test size: {X_test.shape}")

X_train.to_csv(f"{SAVE_DIR}/X_train_raw.csv", index=False)
X_test.to_csv(f"{SAVE_DIR}/X_test_raw.csv", index=False)
y_train.to_csv(f"{SAVE_DIR}/y_train.csv", index=False)
y_test.to_csv(f"{SAVE_DIR}/y_test.csv", index=False)


le = LabelEncoder()

X_train = X_train.copy()
X_test = X_test.copy()

X_train["species_id"] = le.fit_transform(X_train["species"])
X_test["species_id"] = le.transform(X_test["species"])

X_train = X_train.drop(columns=["species"])
X_test = X_test.drop(columns=["species"])

feature_names = X_train.columns.tolist()

logging.info(f"Feature count: {len(feature_names)}")
logging.info(f"Species count: {len(le.classes_)}")


imputer = SimpleImputer(strategy="median")

X_train_processed = pd.DataFrame(
    imputer.fit_transform(X_train),
    columns=feature_names,
    index=X_train.index
)

X_test_processed = pd.DataFrame(
    imputer.transform(X_test),
    columns=feature_names,
    index=X_test.index
)

logging.info(f"NaNs train: {X_train_processed.isna().sum().sum()}")
logging.info(f"NaNs test: {X_test_processed.isna().sum().sum()}")

X_train_processed.to_csv(f"{SAVE_DIR}/X_train_processed.csv", index=False)
X_test_processed.to_csv(f"{SAVE_DIR}/X_test_processed.csv", index=False)


model = get_model()

logging.info("Training enhanced LightGBM...")
model.fit(X_train_processed, y_train)

joblib.dump(model, f"{SAVE_DIR}/phyto_lightgbm_model.pkl")
joblib.dump(le, f"{SAVE_DIR}/species_encoder.pkl")
joblib.dump(imputer, f"{SAVE_DIR}/imputer.pkl")
joblib.dump(feature_names, f"{SAVE_DIR}/feature_names.pkl")

logging.info("Model + artifacts saved ✅")


y_pred = model.predict(X_test_processed)
y_prob = model.predict_proba(X_test_processed)[:, 1]

acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
report = classification_report(y_test, y_pred)

logging.info(f"Accuracy: {acc:.4f}")
logging.info(f"AUC: {auc:.4f}")

print("\nClassification Report:\n")
print(report)

with open(f"{SAVE_DIR}/evaluation_report.txt", "w") as f:
    f.write(f"Accuracy: {acc:.4f}\n")
    f.write(f"AUC: {auc:.4f}\n\n")
    f.write(report)


importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": model.feature_importances_
}).sort_values("importance", ascending=False)

importance_df.to_csv(f"{SAVE_DIR}/feature_importance.csv", index=False)

print("\nTop 15 Features:")
print(importance_df.head(15))


def suitability_class(prob):
    if prob >= 0.75:
        return "Highly suitable"
    elif prob >= 0.50:
        return "Suitable"
    elif prob >= 0.30:
        return "Moderately suitable"
    else:
        return "Low / not suitable"


def predict_species_suitability(city_name, lat, lon, species_name):
    if species_name not in le.classes_:
        raise ValueError(f"{species_name} not found in training species list.")

    env_values = extractor.extract_point(lat, lon)

    base_cols = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

    sample_df = pd.DataFrame(
        [env_values],
        columns=base_cols
    )

    sample_df = add_engineered_features(sample_df)

    sample_df["species_id"] = le.transform([species_name])[0]
    sample_df = sample_df[feature_names]

    sample_processed = pd.DataFrame(
        imputer.transform(sample_df),
        columns=feature_names
    )

    prob = model.predict_proba(sample_processed)[0][1]
    label = int(prob >= 0.5)

    print("====================================")
    print(f"City: {city_name}")
    print(f"Species: {species_name}")
    print(f"Suitability Probability: {prob:.4f}")
    print(f"Suitability Class: {suitability_class(prob)}")
    print(f"Binary Prediction: {'Suitable' if label == 1 else 'Not suitable'}")
    print("====================================")

    return prob, label


predict_species_suitability(
    city_name="Cedars of God",
    lat=34.2436,
    lon=36.0486,
    species_name="Cedrus libani"
)

logging.info("Enhanced v4 pipeline completed successfully 🚀")

2026-05-10 06:01:21,535 - INFO - Logging is working ✅
2026-05-10 06:01:21,541 - INFO - Saving outputs to: /content/drive/MyDrive/PhytoLB/model_enhanced_v4
2026-05-10 06:01:21,615 - INFO - GBIF loaded: 13748 records
2026-05-10 06:01:21,617 - INFO - Unique species: 27
2026-05-10 06:01:21,746 - INFO - Climate + elevation rasters loaded ✅
2026-05-10 06:01:21,749 - INFO - Extracting presence features...
2026-05-10 06:01:21,767 - INFO - Processed 0/13748 points
2026-05-10 06:01:31,946 - INFO - Processed 1000/13748 points
2026-05-10 06:01:41,376 - INFO - Processed 2000/13748 points
2026-05-10 06:01:46,310 - INFO - Processed 3000/13748 points
2026-05-10 06:01:48,961 - INFO - Processed 4000/13748 points
2026-05-10 06:01:51,670 - INFO - Processed 5000/13748 points
2026-05-10 06:01:55,161 - INFO - Processed 6000/13748 points
2026-05-10 06:01:58,488 - INFO - Processed 7000/13748 points
2026-05-10 06:02:01,156 - INFO - Processed 8000/13748 points
2026-05-10 06:02:03,809 - INFO - Processed 9000/13748 points
2026-05-10 06:02:06,479 - INFO - Processed 10000/13748 points
2026-05-10 06:02:10,354 - INFO - Processed 11000/13748 points
2026-05-10 06:02:13,257 - INFO - Processed 12000/13748 points
2026-05-10 06:02:15,902 - INFO - Processed 13000/13748 points
2026-05-10 06:02:17,986 - INFO - Generating filtered pseudo-absence points...
2026-05-10 06:02:22,831 - INFO - Generated 1000/13748 valid pseudo-absences
2026-05-10 06:02:28,266 - INFO - Generated 2000/13748 valid pseudo-absences
2026-05-10 06:02:32,323 - INFO - Generated 3000/13748 valid pseudo-absences
2026-05-10 06:02:37,029 - INFO - Generated 4000/13748 valid pseudo-absences
2026-05-10 06:02:41,939 - INFO - Generated 5000/13748 valid pseudo-absences
2026-05-10 06:02:46,849 - INFO - Generated 6000/13748 valid pseudo-absences
2026-05-10 06:02:51,828 - INFO - Generated 7000/13748 valid pseudo-absences
2026-05-10 06:02:57,227 - INFO - Generated 8000/13748 valid pseudo-absences
2026-05-10 06:03:01,263 - INFO - Generated 9000/13748 valid pseudo-absences
2026-05-10 06:03:07,514 - INFO - Generated 10000/13748 valid pseudo-absences
2026-05-10 06:03:12,860 - INFO - Generated 11000/13748 valid pseudo-absences
2026-05-10 06:03:17,029 - INFO - Generated 12000/13748 valid pseudo-absences
2026-05-10 06:03:22,504 - INFO - Generated 13000/13748 valid pseudo-absences
2026-05-10 06:03:25,558 - INFO - Extracting pseudo-absence features...
2026-05-10 06:03:25,564 - INFO - Processed 0/13748 points
2026-05-10 06:03:28,170 - INFO - Processed 1000/13748 points
2026-05-10 06:03:30,742 - INFO - Processed 2000/13748 points
2026-05-10 06:03:33,806 - INFO - Processed 3000/13748 points
2026-05-10 06:03:37,380 - INFO - Processed 4000/13748 points
2026-05-10 06:03:40,245 - INFO - Processed 5000/13748 points
2026-05-10 06:03:42,998 - INFO - Processed 6000/13748 points
2026-05-10 06:03:45,725 - INFO - Processed 7000/13748 points
2026-05-10 06:03:49,369 - INFO - Processed 8000/13748 points
2026-05-10 06:03:52,547 - INFO - Processed 9000/13748 points
2026-05-10 06:03:55,232 - INFO - Processed 10000/13748 points
2026-05-10 06:03:57,905 - INFO - Processed 11000/13748 points
2026-05-10 06:04:00,535 - INFO - Processed 12000/13748 points
2026-05-10 06:04:04,676 - INFO - Processed 13000/13748 points
2026-05-10 06:04:06,862 - INFO - Dataset before filtering: (27496, 22)
2026-05-10 06:04:06,872 - INFO - Dataset after filtering: (27496, 22)
2026-05-10 06:04:06,880 - INFO - Final dataset shape: (27496, 30)
2026-05-10 06:04:06,882 - INFO - Class distribution:
label
1    13748
0    13748
Name: count, dtype: int64
2026-05-10 06:04:06,887 - INFO - Missing values:
BIO1     0
BIO2     0
BIO3     0
BIO4     0
BIO5     0
BIO6     0
BIO7     0
BIO8     0
BIO9     0
BIO10    0
dtype: int64
2026-05-10 06:04:07,595 - INFO - Final dataset saved ✅
2026-05-10 06:04:07,612 - INFO - Train size: (21996, 29)
2026-05-10 06:04:07,613 - INFO - Test size: (5500, 29)
2026-05-10 06:04:08,335 - INFO - Feature count: 29
2026-05-10 06:04:08,336 - INFO - Species count: 27
2026-05-10 06:04:08,391 - INFO - NaNs train: 0
2026-05-10 06:04:08,393 - INFO - NaNs test: 0
2026-05-10 06:04:09,392 - INFO - Training enhanced LightGBM...
2026-05-10 06:04:14,530 - INFO - Model + artifacts saved ✅
2026-05-10 06:04:16,388 - INFO - Accuracy: 0.9176
2026-05-10 06:04:16,390 - INFO - AUC: 0.9637

Classification Report:

              precision    recall  f1-score   support

           0       0.95      0.88      0.91      2750
           1       0.89      0.95      0.92      2750

    accuracy                           0.92      5500
   macro avg       0.92      0.92      0.92      5500
weighted avg       0.92      0.92      0.92      5500


Top 15 Features:
                         feature  importance
28                    species_id       16289
26    elevation_temp_interaction       11828
19                     elevation       11178
27  elevation_precip_interaction       10921
11                         BIO12        1679
2                           BIO3        1449
14                         BIO15        1259
0                           BIO1        1246
1                           BIO2        1210
25    summer_winter_precip_ratio        1099
4                           BIO5        1037
24                 dryness_ratio         901
3                           BIO4         853
12                         BIO13         764
17                         BIO18         626
====================================
City: Cedars of God
Species: Cedrus libani
Suitability Probability: 0.7216
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
2026-05-10 06:04:16,480 - INFO - Enhanced v4 pipeline completed successfully 🚀

In [ ]:
predict_species_suitability(
    city_name="Beirut",
    lat=33.8938,
    lon=35.5018,
    species_name="Cedrus libani"
)

====================================
City: Beirut
Species: Cedrus libani
Suitability Probability: 0.0342
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.03419956541314632), 0)

In [ ]:
predict_species_suitability(
    city_name="Faraya",
    lat=33.9944,
    lon=35.8172,
    species_name="Abies cilicica"
)

====================================
City: Faraya
Species: Abies cilicica
Suitability Probability: 0.0158
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.01581292199606067), 0)

In [ ]:
predict_species_suitability(
    city_name="Tyre",
    lat=33.2700,
    lon=35.2038,
    species_name="Abies cilicica"
)

====================================
City: Tyre
Species: Abies cilicica
Suitability Probability: 0.0001
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(9.176412586832604e-05), 0)

In [ ]:
predict_species_suitability(
    city_name="Byblos",
    lat=34.1230,
    lon=35.6519,
    species_name="Quercus coccifera calliprinos"
)

====================================
City: Byblos
Species: Quercus coccifera calliprinos
Suitability Probability: 0.8501
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================

(np.float64(0.8501234326481469), 1)

In [ ]:
[x for x in le.classes_ if "Quercus" in x]

['Quercus cedrorum',
 'Quercus cerris',
 'Quercus coccifera calliprinos',
 'Quercus infectoria boissieri',
 'Quercus ithaburensis',
 'Quercus kotschyana',
 'Quercus look']

In [ ]:
predict_species_suitability(
    city_name="Zahle",
    lat=33.8463,
    lon=35.9020,
    species_name="Quercus ithaburensis"
)

====================================
City: Zahle
Species: Quercus ithaburensis
Suitability Probability: 0.0022
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.0021704114998436596), 0)

In [ ]:
predict_species_suitability(
    city_name="Bcharre",
    lat=34.2508,
    lon=36.0106,
    species_name="Quercus infectoria boissieri"
)

====================================
City: Bcharre
Species: Quercus infectoria boissieri
Suitability Probability: 0.8926
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================

(np.float64(0.8926496313467402), 1)

In [ ]:
predict_species_suitability(
    city_name="Sidon",
    lat=33.5630,
    lon=35.3688,
    species_name="Ceratonia siliqua"
)

====================================
City: Sidon
Species: Ceratonia siliqua
Suitability Probability: 0.2775
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.27751182647930783), 0)

In [ ]:
predict_species_suitability(
    city_name="Faraya",
    lat=33.9944,
    lon=35.8172,
    species_name="Ceratonia siliqua"
)

====================================
City: Faraya
Species: Ceratonia siliqua
Suitability Probability: 0.0143
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.01428339155307848), 0)

In [ ]:
predict_species_suitability(
    city_name="Jbeil",
    lat=34.1217,
    lon=35.6481,
    species_name="Arbutus andrachne"
)

====================================
City: Jbeil
Species: Arbutus andrachne
Suitability Probability: 0.6640
Suitability Class: Suitable
Binary Prediction: Suitable
====================================

(np.float64(0.6639694479836706), 1)

In [ ]:
predict_species_suitability(
    city_name="Baalbek",
    lat=34.0060,
    lon=36.2181,
    species_name="Juniperus excelsa"
)

====================================
City: Baalbek
Species: Juniperus excelsa
Suitability Probability: 0.1370
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.13700073602680754), 0)

In [ ]:
predict_species_suitability(
    city_name="Faraya",
    lat=33.9944,
    lon=35.8172,
    species_name="Juniperus drupacea"
)

====================================
City: Faraya
Species: Juniperus drupacea
Suitability Probability: 0.0779
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.07792286859349763), 0)

In [ ]:
predict_species_suitability(
    city_name="Tyre",
    lat=33.2700,
    lon=35.2038,
    species_name="Cedrus libani"
)

====================================
City: Tyre
Species: Cedrus libani
Suitability Probability: 0.0006
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.0005952741584186892), 0)

In [ ]:
predict_species_suitability(
    city_name="Bcharre",
    lat=34.2508,
    lon=36.0106,
    species_name="Ceratonia siliqua"
)

====================================
City: Bcharre
Species: Ceratonia siliqua
Suitability Probability: 0.1003
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.1003403730393415), 0)

In [ ]:
predict_species_suitability(
    city_name="Beirut",
    lat=33.8938,
    lon=35.5018,
    species_name="Abies cilicica"
)

====================================
City: Beirut
Species: Abies cilicica
Suitability Probability: 0.0009
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

(np.float64(0.0009157715537510458), 0)

In [ ]:
cities = [
    ("Beirut", 33.8938, 35.5018),
    ("Faraya", 33.9944, 35.8172),
    ("Bcharre", 34.2508, 36.0106),
    ("Tyre", 33.2700, 35.2038),
]

species_list = [
    "Cedrus libani",
    "Ceratonia siliqua",
    "Abies cilicica",
]

for city_name, lat, lon in cities:
    for sp in species_list:
        predict_species_suitability(
            city_name,
            lat,
            lon,
            sp
        )

====================================
City: Beirut
Species: Cedrus libani
Suitability Probability: 0.0342
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Ceratonia siliqua
Suitability Probability: 0.8009
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Beirut
Species: Abies cilicica
Suitability Probability: 0.0009
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Cedrus libani
Suitability Probability: 0.3607
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Ceratonia siliqua
Suitability Probability: 0.0143
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Abies cilicica
Suitability Probability: 0.0158
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Cedrus libani
Suitability Probability: 0.5662
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Ceratonia siliqua
Suitability Probability: 0.1003
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Abies cilicica
Suitability Probability: 0.4753
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tyre
Species: Cedrus libani
Suitability Probability: 0.0006
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tyre
Species: Ceratonia siliqua
Suitability Probability: 0.0276
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tyre
Species: Abies cilicica
Suitability Probability: 0.0001
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================

In [ ]:
abies = gbif[gbif["species"] == "Abies cilicica"]

print(abies.shape)

print(abies[["lat", "lon"]].describe())

(576, 3)
              lat         lon
count  576.000000  576.000000
mean    34.451117   36.191212
std      0.048232    0.059169
min     34.300800   35.985596
25%     34.412894   36.160012
50%     34.473156   36.216878
75%     34.490025   36.231046
max     34.517700   36.278457

## Enhanced V5

In [ ]:
# ============================================================
# PhytoLB Enhanced Pipeline v5
# Climate + Elevation + Engineered Features + LightGBM
# Saves datasets, model, artifacts, diagnostics, predictions
# ============================================================

# -----------------------
# 0. Imports
# -----------------------
import os
import sys
import joblib
import logging
import numpy as np
import pandas as pd
import rasterio
import lightgbm as lgb

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix


# -----------------------
# 1. Logging
# -----------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
    force=True
)

logging.info("Logging is working ✅")


# -----------------------
# 2. Paths
# -----------------------
BASE_DIR = "/content/drive/MyDrive/PhytoLB"

GBIF_PATH = f"{BASE_DIR}/dwca-tree_lebanon-v1.0/occurrence.txt"
CLIMATE_DIR = f"{BASE_DIR}/wc2.1_10m_bio"
ELEVATION_PATH = f"{BASE_DIR}/elevation/elevation.tif"

SAVE_DIR = f"{BASE_DIR}/model_enhanced_v5"
os.makedirs(SAVE_DIR, exist_ok=True)

logging.info(f"Saving outputs to: {SAVE_DIR}")


# -----------------------
# 3. Load GBIF
# -----------------------
def load_gbif_txt(path):
    df = pd.read_csv(path, sep="\t", low_memory=False)

    if "species" not in df.columns:
        df["species"] = df["scientificName"]

    df = df[["species", "decimalLatitude", "decimalLongitude"]]
    df = df.dropna()

    df.columns = ["species", "lat", "lon"]

    df["lat"] = pd.to_numeric(df["lat"], errors="coerce")
    df["lon"] = pd.to_numeric(df["lon"], errors="coerce")
    df = df.dropna()

    # Lebanon approximate bounding box
    df = df[
        (df["lat"] >= 33.0) & (df["lat"] <= 34.8) &
        (df["lon"] >= 35.0) & (df["lon"] <= 36.8)
    ]

    df = df.drop_duplicates()

    logging.info(f"GBIF loaded: {len(df)} records")
    logging.info(f"Unique species: {df['species'].nunique()}")

    return df


# -----------------------
# 4. Environmental Extractor
# -----------------------
class EnvironmentalExtractor:
    def __init__(self, climate_folder, elevation_path):
        self.climate_rasters = []

        for i in range(1, 20):
            path = os.path.join(climate_folder, f"wc2.1_10m_bio_{i}.tif")

            if not os.path.exists(path):
                raise FileNotFoundError(f"Missing climate file: {path}")

            self.climate_rasters.append(rasterio.open(path))

        if not os.path.exists(elevation_path):
            raise FileNotFoundError(f"Missing elevation file: {elevation_path}")

        self.elevation_raster = rasterio.open(elevation_path)

        logging.info("Climate + elevation rasters loaded ✅")

    def extract_point(self, lat, lon):
        values = []

        for raster in self.climate_rasters:
            try:
                val = next(raster.sample([(lon, lat)]))[0]

                if raster.nodata is not None and val == raster.nodata:
                    val = np.nan

            except Exception:
                val = np.nan

            values.append(val)

        try:
            elev = next(self.elevation_raster.sample([(lon, lat)]))[0]

            if self.elevation_raster.nodata is not None and elev == self.elevation_raster.nodata:
                elev = np.nan

        except Exception:
            elev = np.nan

        values.append(elev)

        return values

    def extract_dataframe(self, df):
        features = []
        total = len(df)

        for i, row in enumerate(df.itertuples(index=False)):
            values = self.extract_point(row.lat, row.lon)
            features.append(values)

            if i % 1000 == 0:
                logging.info(f"Processed {i}/{total} points")

        columns = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

        return pd.DataFrame(features, columns=columns)


# -----------------------
# 5. Feature Engineering
# -----------------------
def add_engineered_features(df):
    df = df.copy()

    df["temp_annual_range"] = df["BIO5"] - df["BIO6"]
    df["warm_cold_quarter_diff"] = df["BIO10"] - df["BIO11"]

    df["precip_wet_dry_month_diff"] = df["BIO13"] - df["BIO14"]
    df["precip_wet_dry_quarter_diff"] = df["BIO16"] - df["BIO17"]

    df["dryness_ratio"] = df["BIO17"] / (df["BIO16"] + 1e-6)
    df["summer_winter_precip_ratio"] = df["BIO18"] / (df["BIO19"] + 1e-6)

    df["elevation_temp_interaction"] = df["elevation"] * df["BIO1"]
    df["elevation_precip_interaction"] = df["elevation"] * df["BIO12"]

    return df


# -----------------------
# 6. Filtered Pseudo-Absence Generation
# -----------------------
def generate_pseudo_absence(df, n_samples, extractor, random_state=42):
    np.random.seed(random_state)

    lat_min, lat_max = df["lat"].min(), df["lat"].max()
    lon_min, lon_max = df["lon"].min(), df["lon"].max()

    pseudo_rows = []
    attempts = 0
    max_attempts = n_samples * 20

    logging.info("Generating filtered pseudo-absence points...")

    while len(pseudo_rows) < n_samples and attempts < max_attempts:
        attempts += 1

        lat = np.random.uniform(lat_min, lat_max)
        lon = np.random.uniform(lon_min, lon_max)

        values = extractor.extract_point(lat, lon)

        # Reject invalid environmental points
        if np.isnan(values).sum() > 0:
            continue

        elevation = values[-1]

        # Reject sea / invalid terrain
        if elevation < 0 or elevation > 3200:
            continue

        species = df["species"].sample(
            1,
            random_state=np.random.randint(0, 999999)
        ).iloc[0]

        pseudo_rows.append({
            "species": species,
            "lat": lat,
            "lon": lon,
            "label": 0
        })

        if len(pseudo_rows) % 1000 == 0:
            logging.info(f"Generated {len(pseudo_rows)}/{n_samples} valid pseudo-absences")

    pseudo_df = pd.DataFrame(pseudo_rows)

    if len(pseudo_df) < n_samples:
        logging.warning(f"Only generated {len(pseudo_df)} pseudo-absences out of {n_samples}")

    return pseudo_df


# -----------------------
# 7. Build Dataset
# -----------------------
def build_dataset(df, extractor):
    logging.info("Extracting presence features...")

    presence_features = extractor.extract_dataframe(df)
    presence_features["species"] = df["species"].values
    presence_features["lat"] = df["lat"].values
    presence_features["lon"] = df["lon"].values
    presence_features["label"] = 1

    pseudo_df = generate_pseudo_absence(
        df=df,
        n_samples=len(df),
        extractor=extractor,
        random_state=42
    )

    logging.info("Extracting pseudo-absence features...")

    absence_features = extractor.extract_dataframe(pseudo_df)
    absence_features["species"] = pseudo_df["species"].values
    absence_features["lat"] = pseudo_df["lat"].values
    absence_features["lon"] = pseudo_df["lon"].values
    absence_features["label"] = 0

    full_df = pd.concat([presence_features, absence_features], ignore_index=True)

    logging.info(f"Dataset before filtering: {full_df.shape}")

    env_cols = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]
    full_df = full_df.dropna(subset=env_cols)

    logging.info(f"Dataset after filtering: {full_df.shape}")

    full_df = add_engineered_features(full_df)

    return full_df


# -----------------------
# 8. Model
# -----------------------
def get_model():
    return lgb.LGBMClassifier(
        objective="binary",
        n_estimators=900,
        learning_rate=0.02,
        max_depth=9,
        num_leaves=80,
        min_child_samples=15,
        subsample=0.9,
        subsample_freq=1,
        colsample_bytree=0.9,
        reg_alpha=0.05,
        reg_lambda=0.3,
        random_state=42,
        force_row_wise=True,
        verbose=-1
    )


# -----------------------
# 9. Helpers
# -----------------------
def suitability_class(prob):
    if prob >= 0.75:
        return "Highly suitable"
    elif prob >= 0.50:
        return "Suitable"
    elif prob >= 0.30:
        return "Moderately suitable"
    else:
        return "Low / not suitable"


def find_species(name_part):
    matches = [sp for sp in le.classes_ if name_part.lower() in sp.lower()]

    if not matches:
        print("No species found.")
    else:
        for sp in matches:
            print(sp)


def species_distribution(species_name):
    subset = gbif[gbif["species"] == species_name]

    if subset.empty:
        print(f"{species_name} not found.")
        return None

    print(f"\nSpecies: {species_name}")
    print(f"Records: {len(subset)}")
    print(subset[["lat", "lon"]].describe())

    return subset


# ============================================================
# MAIN PIPELINE
# ============================================================

# -----------------------
# 10. Load Data
# -----------------------
gbif = load_gbif_txt(GBIF_PATH)
gbif.to_csv(f"{SAVE_DIR}/clean_gbif.csv", index=False)

species_counts = gbif["species"].value_counts().reset_index()
species_counts.columns = ["species", "records"]
species_counts.to_csv(f"{SAVE_DIR}/species_counts.csv", index=False)


# -----------------------
# 11. Initialize Extractor
# -----------------------
extractor = EnvironmentalExtractor(
    climate_folder=CLIMATE_DIR,
    elevation_path=ELEVATION_PATH
)


# -----------------------
# 12. Build Dataset
# -----------------------
dataset = build_dataset(gbif, extractor)

logging.info(f"Final dataset shape: {dataset.shape}")
logging.info(f"Class distribution:\n{dataset['label'].value_counts()}")
logging.info(f"Missing values total: {dataset.isna().sum().sum()}")

dataset.to_csv(f"{SAVE_DIR}/final_phyto_dataset.csv", index=False)
dataset.to_parquet(f"{SAVE_DIR}/final_phyto_dataset.parquet", index=False)


# -----------------------
# 13. Split
# -----------------------
X = dataset.drop(columns=["label"])
y = dataset["label"]

# Keep coordinates for diagnostics, but remove from model features later
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

logging.info(f"Train size: {X_train.shape}")
logging.info(f"Test size: {X_test.shape}")

X_train.to_csv(f"{SAVE_DIR}/X_train_raw.csv", index=False)
X_test.to_csv(f"{SAVE_DIR}/X_test_raw.csv", index=False)
y_train.to_csv(f"{SAVE_DIR}/y_train.csv", index=False)
y_test.to_csv(f"{SAVE_DIR}/y_test.csv", index=False)


# -----------------------
# 14. Encode Species
# -----------------------
le = LabelEncoder()

X_train = X_train.copy()
X_test = X_test.copy()

X_train["species_id"] = le.fit_transform(X_train["species"])
X_test["species_id"] = le.transform(X_test["species"])

# Save diagnostic columns separately
train_diagnostics = X_train[["species", "lat", "lon"]].copy()
test_diagnostics = X_test[["species", "lat", "lon"]].copy()

train_diagnostics.to_csv(f"{SAVE_DIR}/train_diagnostics.csv", index=False)
test_diagnostics.to_csv(f"{SAVE_DIR}/test_diagnostics.csv", index=False)

# Drop non-model columns
X_train = X_train.drop(columns=["species", "lat", "lon"])
X_test = X_test.drop(columns=["species", "lat", "lon"])

feature_names = X_train.columns.tolist()

logging.info(f"Feature count: {len(feature_names)}")
logging.info(f"Species count: {len(le.classes_)}")


# -----------------------
# 15. Impute
# -----------------------
imputer = SimpleImputer(strategy="median")

X_train_processed = pd.DataFrame(
    imputer.fit_transform(X_train),
    columns=feature_names,
    index=X_train.index
)

X_test_processed = pd.DataFrame(
    imputer.transform(X_test),
    columns=feature_names,
    index=X_test.index
)

logging.info(f"NaNs train: {X_train_processed.isna().sum().sum()}")
logging.info(f"NaNs test: {X_test_processed.isna().sum().sum()}")

X_train_processed.to_csv(f"{SAVE_DIR}/X_train_processed.csv", index=False)
X_test_processed.to_csv(f"{SAVE_DIR}/X_test_processed.csv", index=False)


# -----------------------
# 16. Train
# -----------------------
model = get_model()

logging.info("Training enhanced LightGBM...")
model.fit(X_train_processed, y_train)

joblib.dump(model, f"{SAVE_DIR}/phyto_lightgbm_model.pkl")
joblib.dump(le, f"{SAVE_DIR}/species_encoder.pkl")
joblib.dump(imputer, f"{SAVE_DIR}/imputer.pkl")
joblib.dump(feature_names, f"{SAVE_DIR}/feature_names.pkl")

logging.info("Model + artifacts saved ✅")


# -----------------------
# 17. Evaluate
# -----------------------
y_pred = model.predict(X_test_processed)
y_prob = model.predict_proba(X_test_processed)[:, 1]

acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
report = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

logging.info(f"Accuracy: {acc:.4f}")
logging.info(f"AUC: {auc:.4f}")

print("\nClassification Report:\n")
print(report)

print("\nConfusion Matrix:")
print(cm)

with open(f"{SAVE_DIR}/evaluation_report.txt", "w") as f:
    f.write(f"Accuracy: {acc:.4f}\n")
    f.write(f"AUC: {auc:.4f}\n\n")
    f.write("Classification Report:\n")
    f.write(report)
    f.write("\nConfusion Matrix:\n")
    f.write(str(cm))


# -----------------------
# 18. Feature Importance
# -----------------------
importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": model.feature_importances_
}).sort_values("importance", ascending=False)

importance_df.to_csv(f"{SAVE_DIR}/feature_importance.csv", index=False)

print("\nTop 15 Features:")
print(importance_df.head(15))


# -----------------------
# 19. Prediction Function
# -----------------------
def predict_species_suitability(city_name, lat, lon, species_name):
    if species_name not in le.classes_:
        print(f"'{species_name}' not found.")
        print("Closest matches:")
        for sp in le.classes_:
            if species_name.split()[0].lower() in sp.lower():
                print("-", sp)
        return None

    env_values = extractor.extract_point(lat, lon)

    base_cols = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

    sample_df = pd.DataFrame([env_values], columns=base_cols)

    sample_df = add_engineered_features(sample_df)

    sample_df["species_id"] = le.transform([species_name])[0]
    sample_df = sample_df[feature_names]

    sample_processed = pd.DataFrame(
        imputer.transform(sample_df),
        columns=feature_names
    )

    prob = model.predict_proba(sample_processed)[0][1]
    label = int(prob >= 0.5)

    print("====================================")
    print(f"City: {city_name}")
    print(f"Species: {species_name}")
    print(f"Suitability Probability: {prob:.4f}")
    print(f"Suitability Class: {suitability_class(prob)}")
    print(f"Binary Prediction: {'Suitable' if label == 1 else 'Not suitable'}")
    print("====================================")

    return float(prob), label


# -----------------------
# 20. Batch Prediction Function
# -----------------------
def batch_predict(cities, species_list):
    results = []

    for city_name, lat, lon in cities:
        for species_name in species_list:
            output = predict_species_suitability(city_name, lat, lon, species_name)

            if output is None:
                continue

            prob, label = output

            results.append({
                "city": city_name,
                "lat": lat,
                "lon": lon,
                "species": species_name,
                "probability": prob,
                "class": suitability_class(prob),
                "binary_label": label
            })

    results_df = pd.DataFrame(results)
    results_df.to_csv(f"{SAVE_DIR}/city_species_predictions.csv", index=False)

    return results_df


# -----------------------
# 21. Test Samples
# -----------------------
test_cities = [
    ("Beirut", 33.8938, 35.5018),
    ("Tripoli", 34.4367, 35.8497),
    ("Byblos", 34.1230, 35.6519),
    ("Bcharre", 34.2508, 36.0106),
    ("Cedars of God", 34.2436, 36.0486),
    ("Faraya", 33.9944, 35.8172),
    ("Zahle", 33.8463, 35.9020),
    ("Baalbek", 34.0060, 36.2181),
    ("Sidon", 33.5630, 35.3688),
    ("Tyre", 33.2700, 35.2038)
]

test_species = [
    "Cedrus libani",
    "Ceratonia siliqua",
    "Abies cilicica",
    "Quercus coccifera calliprinos",
    "Quercus infectoria boissieri",
    "Arbutus andrachne",
    "Juniperus excelsa",
    "Juniperus drupacea"
]

predictions_df = batch_predict(test_cities, test_species)

print("\nPrediction summary:")
print(predictions_df.sort_values("probability", ascending=False).head(20))

logging.info("Enhanced v5 pipeline completed successfully 🚀")

2026-05-10 06:21:57,612 - INFO - Logging is working ✅
2026-05-10 06:21:57,630 - INFO - Saving outputs to: /content/drive/MyDrive/PhytoLB/model_enhanced_v5
2026-05-10 06:21:57,744 - INFO - GBIF loaded: 13748 records
2026-05-10 06:21:57,747 - INFO - Unique species: 27
2026-05-10 06:21:57,928 - INFO - Climate + elevation rasters loaded ✅
2026-05-10 06:21:57,935 - INFO - Extracting presence features...
2026-05-10 06:21:57,955 - INFO - Processed 0/13748 points
2026-05-10 06:22:00,958 - INFO - Processed 1000/13748 points
2026-05-10 06:22:03,617 - INFO - Processed 2000/13748 points
2026-05-10 06:22:06,366 - INFO - Processed 3000/13748 points
2026-05-10 06:22:09,505 - INFO - Processed 4000/13748 points
2026-05-10 06:22:13,611 - INFO - Processed 5000/13748 points
2026-05-10 06:22:16,323 - INFO - Processed 6000/13748 points
2026-05-10 06:22:19,131 - INFO - Processed 7000/13748 points
2026-05-10 06:22:21,974 - INFO - Processed 8000/13748 points
2026-05-10 06:22:25,525 - INFO - Processed 9000/13748 points
2026-05-10 06:22:29,097 - INFO - Processed 10000/13748 points
2026-05-10 06:22:31,844 - INFO - Processed 11000/13748 points
2026-05-10 06:22:34,649 - INFO - Processed 12000/13748 points
2026-05-10 06:22:37,401 - INFO - Processed 13000/13748 points
2026-05-10 06:22:40,789 - INFO - Generating filtered pseudo-absence points...
2026-05-10 06:22:46,624 - INFO - Generated 1000/13748 valid pseudo-absences
2026-05-10 06:22:50,961 - INFO - Generated 2000/13748 valid pseudo-absences
2026-05-10 06:22:56,875 - INFO - Generated 3000/13748 valid pseudo-absences
2026-05-10 06:23:01,280 - INFO - Generated 4000/13748 valid pseudo-absences
2026-05-10 06:23:05,735 - INFO - Generated 5000/13748 valid pseudo-absences
2026-05-10 06:23:11,838 - INFO - Generated 6000/13748 valid pseudo-absences
2026-05-10 06:23:16,439 - INFO - Generated 7000/13748 valid pseudo-absences
2026-05-10 06:23:20,766 - INFO - Generated 8000/13748 valid pseudo-absences
2026-05-10 06:23:26,599 - INFO - Generated 9000/13748 valid pseudo-absences
2026-05-10 06:23:30,715 - INFO - Generated 10000/13748 valid pseudo-absences
2026-05-10 06:23:35,971 - INFO - Generated 11000/13748 valid pseudo-absences
2026-05-10 06:23:41,456 - INFO - Generated 12000/13748 valid pseudo-absences
2026-05-10 06:23:45,575 - INFO - Generated 13000/13748 valid pseudo-absences
2026-05-10 06:23:48,674 - INFO - Extracting pseudo-absence features...
2026-05-10 06:23:48,680 - INFO - Processed 0/13748 points
2026-05-10 06:23:52,196 - INFO - Processed 1000/13748 points
2026-05-10 06:23:55,460 - INFO - Processed 2000/13748 points
2026-05-10 06:23:58,099 - INFO - Processed 3000/13748 points
2026-05-10 06:24:00,696 - INFO - Processed 4000/13748 points
2026-05-10 06:24:03,403 - INFO - Processed 5000/13748 points
2026-05-10 06:24:07,289 - INFO - Processed 6000/13748 points
2026-05-10 06:24:10,191 - INFO - Processed 7000/13748 points
2026-05-10 06:24:12,814 - INFO - Processed 8000/13748 points
2026-05-10 06:24:15,476 - INFO - Processed 9000/13748 points
2026-05-10 06:24:18,353 - INFO - Processed 10000/13748 points
2026-05-10 06:24:22,457 - INFO - Processed 11000/13748 points
2026-05-10 06:24:25,089 - INFO - Processed 12000/13748 points
2026-05-10 06:24:27,713 - INFO - Processed 13000/13748 points
2026-05-10 06:24:29,781 - INFO - Dataset before filtering: (27496, 24)
2026-05-10 06:24:29,787 - INFO - Dataset after filtering: (27496, 24)
2026-05-10 06:24:29,794 - INFO - Final dataset shape: (27496, 32)
2026-05-10 06:24:29,795 - INFO - Class distribution:
label
1    13748
0    13748
Name: count, dtype: int64
2026-05-10 06:24:29,801 - INFO - Missing values total: 0
2026-05-10 06:24:30,659 - INFO - Train size: (21996, 31)
2026-05-10 06:24:30,660 - INFO - Test size: (5500, 31)
2026-05-10 06:24:31,595 - INFO - Feature count: 29
2026-05-10 06:24:31,596 - INFO - Species count: 27
2026-05-10 06:24:31,650 - INFO - NaNs train: 0
2026-05-10 06:24:31,652 - INFO - NaNs test: 0
2026-05-10 06:24:33,029 - INFO - Training enhanced LightGBM...
2026-05-10 06:24:39,358 - INFO - Model + artifacts saved ✅
2026-05-10 06:24:41,059 - INFO - Accuracy: 0.9171
2026-05-10 06:24:41,060 - INFO - AUC: 0.9627

Classification Report:

              precision    recall  f1-score   support

           0       0.95      0.88      0.91      2750
           1       0.89      0.96      0.92      2750

    accuracy                           0.92      5500
   macro avg       0.92      0.92      0.92      5500
weighted avg       0.92      0.92      0.92      5500


Confusion Matrix:
[[2410  340]
 [ 116 2634]]

Top 15 Features:
                         feature  importance
28                    species_id       16432
26    elevation_temp_interaction       11534
19                     elevation       11333
27  elevation_precip_interaction       10874
11                         BIO12        1556
2                           BIO3        1453
14                         BIO15        1328
0                           BIO1        1239
1                           BIO2        1217
4                           BIO5        1066
25    summer_winter_precip_ratio        1035
24                 dryness_ratio         930
12                         BIO13         812
3                           BIO4         810
17                         BIO18         644
====================================
City: Beirut
Species: Cedrus libani
Suitability Probability: 0.0156
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Ceratonia siliqua
Suitability Probability: 0.7124
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Beirut
Species: Abies cilicica
Suitability Probability: 0.0005
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Quercus coccifera calliprinos
Suitability Probability: 0.7055
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Beirut
Species: Quercus infectoria boissieri
Suitability Probability: 0.1617
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Arbutus andrachne
Suitability Probability: 0.3799
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Juniperus excelsa
Suitability Probability: 0.0096
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Juniperus drupacea
Suitability Probability: 0.0090
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Cedrus libani
Suitability Probability: 0.0134
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Ceratonia siliqua
Suitability Probability: 0.8001
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Tripoli
Species: Abies cilicica
Suitability Probability: 0.0015
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0574
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Quercus infectoria boissieri
Suitability Probability: 0.0214
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Arbutus andrachne
Suitability Probability: 0.3182
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Juniperus excelsa
Suitability Probability: 0.0013
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Juniperus drupacea
Suitability Probability: 0.0015
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Cedrus libani
Suitability Probability: 0.1229
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Ceratonia siliqua
Suitability Probability: 0.9509
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Byblos
Species: Abies cilicica
Suitability Probability: 0.0026
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Quercus coccifera calliprinos
Suitability Probability: 0.9086
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Byblos
Species: Quercus infectoria boissieri
Suitability Probability: 0.1088
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Arbutus andrachne
Suitability Probability: 0.8088
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Byblos
Species: Juniperus excelsa
Suitability Probability: 0.0234
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Juniperus drupacea
Suitability Probability: 0.0287
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Cedrus libani
Suitability Probability: 0.5326
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Ceratonia siliqua
Suitability Probability: 0.0981
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Abies cilicica
Suitability Probability: 0.3961
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Quercus coccifera calliprinos
Suitability Probability: 0.8484
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Quercus infectoria boissieri
Suitability Probability: 0.8819
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Arbutus andrachne
Suitability Probability: 0.3869
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Juniperus excelsa
Suitability Probability: 0.9544
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Juniperus drupacea
Suitability Probability: 0.5885
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Cedars of God
Species: Cedrus libani
Suitability Probability: 0.6745
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Cedars of God
Species: Ceratonia siliqua
Suitability Probability: 0.0554
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Abies cilicica
Suitability Probability: 0.7076
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Cedars of God
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0455
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Quercus infectoria boissieri
Suitability Probability: 0.0928
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Arbutus andrachne
Suitability Probability: 0.3613
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Juniperus excelsa
Suitability Probability: 0.9061
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Cedars of God
Species: Juniperus drupacea
Suitability Probability: 0.0786
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Cedrus libani
Suitability Probability: 0.5069
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Faraya
Species: Ceratonia siliqua
Suitability Probability: 0.0210
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Abies cilicica
Suitability Probability: 0.0143
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Quercus coccifera calliprinos
Suitability Probability: 0.2635
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Quercus infectoria boissieri
Suitability Probability: 0.7188
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Faraya
Species: Arbutus andrachne
Suitability Probability: 0.0364
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Juniperus excelsa
Suitability Probability: 0.1986
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Juniperus drupacea
Suitability Probability: 0.0660
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Cedrus libani
Suitability Probability: 0.0018
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Ceratonia siliqua
Suitability Probability: 0.0045
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Abies cilicica
Suitability Probability: 0.0012
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0777
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Quercus infectoria boissieri
Suitability Probability: 0.0802
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Arbutus andrachne
Suitability Probability: 0.0133
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Juniperus excelsa
Suitability Probability: 0.0328
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Juniperus drupacea
Suitability Probability: 0.0046
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Cedrus libani
Suitability Probability: 0.0030
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Ceratonia siliqua
Suitability Probability: 0.0033
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Abies cilicica
Suitability Probability: 0.0009
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Quercus coccifera calliprinos
Suitability Probability: 0.3000
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Quercus infectoria boissieri
Suitability Probability: 0.0892
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Arbutus andrachne
Suitability Probability: 0.0150
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Juniperus excelsa
Suitability Probability: 0.0858
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Juniperus drupacea
Suitability Probability: 0.0075
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Sidon
Species: Cedrus libani
Suitability Probability: 0.0050
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Sidon
Species: Ceratonia siliqua
Suitability Probability: 0.2712
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Sidon
Species: Abies cilicica
Suitability Probability: 0.0008
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Sidon
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0260
Suitability Class: Low / not suitable
Binary Prediction: Not suitable

# Catboost

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# ============================================================
# PhytoLB CatBoost Pipeline v1
# Climate + Elevation + Engineered Features + CatBoost
# ============================================================

# -----------------------
# 0. Install CatBoost
# -----------------------
!pip install catboost -q

# -----------------------
# 1. Imports
# -----------------------
import os
import sys
import joblib
import logging
import numpy as np
import pandas as pd
import rasterio

from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

# -----------------------
# 2. Logging
# -----------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
    force=True
)

logging.info("Logging is working ✅")

# -----------------------
# 3. Paths
# -----------------------
BASE_DIR = "/content/drive/MyDrive/PhytoLB"

GBIF_PATH = f"{BASE_DIR}/dwca-tree_lebanon-v1.0/occurrence.txt"
CLIMATE_DIR = f"{BASE_DIR}/wc2.1_10m_bio"
ELEVATION_PATH = f"{BASE_DIR}/elevation/elevation.tif"

SAVE_DIR = f"{BASE_DIR}/model_catboost_v1"
os.makedirs(SAVE_DIR, exist_ok=True)

logging.info(f"Saving outputs to: {SAVE_DIR}")


# -----------------------
# 4. Load GBIF
# -----------------------
def load_gbif_txt(path):
    df = pd.read_csv(path, sep="\t", low_memory=False)

    if "species" not in df.columns:
        df["species"] = df["scientificName"]

    df = df[["species", "decimalLatitude", "decimalLongitude"]]
    df = df.dropna()

    df.columns = ["species", "lat", "lon"]

    df["lat"] = pd.to_numeric(df["lat"], errors="coerce")
    df["lon"] = pd.to_numeric(df["lon"], errors="coerce")
    df = df.dropna()

    df = df[
        (df["lat"] >= 33.0) & (df["lat"] <= 34.8) &
        (df["lon"] >= 35.0) & (df["lon"] <= 36.8)
    ]

    df = df.drop_duplicates()

    logging.info(f"GBIF loaded: {len(df)} records")
    logging.info(f"Unique species: {df['species'].nunique()}")

    return df


# -----------------------
# 5. Environmental Extractor
# -----------------------
class EnvironmentalExtractor:
    def __init__(self, climate_folder, elevation_path):
        self.climate_rasters = []

        for i in range(1, 20):
            path = os.path.join(climate_folder, f"wc2.1_10m_bio_{i}.tif")

            if not os.path.exists(path):
                raise FileNotFoundError(f"Missing climate file: {path}")

            self.climate_rasters.append(rasterio.open(path))

        if not os.path.exists(elevation_path):
            raise FileNotFoundError(f"Missing elevation file: {elevation_path}")

        self.elevation_raster = rasterio.open(elevation_path)

        logging.info("Climate + elevation rasters loaded ✅")

    def extract_point(self, lat, lon):
        values = []

        for raster in self.climate_rasters:
            try:
                val = next(raster.sample([(lon, lat)]))[0]

                if raster.nodata is not None and val == raster.nodata:
                    val = np.nan

            except Exception:
                val = np.nan

            values.append(val)

        try:
            elev = next(self.elevation_raster.sample([(lon, lat)]))[0]

            if self.elevation_raster.nodata is not None and elev == self.elevation_raster.nodata:
                elev = np.nan

        except Exception:
            elev = np.nan

        values.append(elev)

        return values

    def extract_dataframe(self, df):
        features = []
        total = len(df)

        for i, row in enumerate(df.itertuples(index=False)):
            values = self.extract_point(row.lat, row.lon)
            features.append(values)

            if i % 1000 == 0:
                logging.info(f"Processed {i}/{total} points")

        columns = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

        return pd.DataFrame(features, columns=columns)


# -----------------------
# 6. Feature Engineering
# -----------------------
def add_engineered_features(df):
    df = df.copy()

    df["temp_annual_range"] = df["BIO5"] - df["BIO6"]
    df["warm_cold_quarter_diff"] = df["BIO10"] - df["BIO11"]

    df["precip_wet_dry_month_diff"] = df["BIO13"] - df["BIO14"]
    df["precip_wet_dry_quarter_diff"] = df["BIO16"] - df["BIO17"]

    df["dryness_ratio"] = df["BIO17"] / (df["BIO16"] + 1e-6)
    df["summer_winter_precip_ratio"] = df["BIO18"] / (df["BIO19"] + 1e-6)

    df["elevation_temp_interaction"] = df["elevation"] * df["BIO1"]
    df["elevation_precip_interaction"] = df["elevation"] * df["BIO12"]

    return df


# -----------------------
# 7. Filtered Pseudo-Absence
# -----------------------
def generate_pseudo_absence(df, n_samples, extractor, random_state=42):
    np.random.seed(random_state)

    lat_min, lat_max = df["lat"].min(), df["lat"].max()
    lon_min, lon_max = df["lon"].min(), df["lon"].max()

    pseudo_rows = []
    attempts = 0
    max_attempts = n_samples * 20

    logging.info("Generating filtered pseudo-absence points...")

    while len(pseudo_rows) < n_samples and attempts < max_attempts:
        attempts += 1

        lat = np.random.uniform(lat_min, lat_max)
        lon = np.random.uniform(lon_min, lon_max)

        values = extractor.extract_point(lat, lon)

        if np.isnan(values).sum() > 0:
            continue

        elevation = values[-1]

        if elevation < 0 or elevation > 3200:
            continue

        species = df["species"].sample(
            1,
            random_state=np.random.randint(0, 999999)
        ).iloc[0]

        pseudo_rows.append({
            "species": species,
            "lat": lat,
            "lon": lon,
            "label": 0
        })

        if len(pseudo_rows) % 1000 == 0:
            logging.info(f"Generated {len(pseudo_rows)}/{n_samples} valid pseudo-absences")

    pseudo_df = pd.DataFrame(pseudo_rows)

    if len(pseudo_df) < n_samples:
        logging.warning(f"Only generated {len(pseudo_df)} pseudo-absences out of {n_samples}")

    return pseudo_df


# -----------------------
# 8. Build Dataset
# -----------------------
def build_dataset(df, extractor):
    logging.info("Extracting presence features...")

    presence_features = extractor.extract_dataframe(df)
    presence_features["species"] = df["species"].values
    presence_features["lat"] = df["lat"].values
    presence_features["lon"] = df["lon"].values
    presence_features["label"] = 1

    pseudo_df = generate_pseudo_absence(
        df=df,
        n_samples=len(df),
        extractor=extractor,
        random_state=42
    )

    logging.info("Extracting pseudo-absence features...")

    absence_features = extractor.extract_dataframe(pseudo_df)
    absence_features["species"] = pseudo_df["species"].values
    absence_features["lat"] = pseudo_df["lat"].values
    absence_features["lon"] = pseudo_df["lon"].values
    absence_features["label"] = 0

    full_df = pd.concat([presence_features, absence_features], ignore_index=True)

    logging.info(f"Dataset before filtering: {full_df.shape}")

    env_cols = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]
    full_df = full_df.dropna(subset=env_cols)

    full_df = add_engineered_features(full_df)

    logging.info(f"Dataset after feature engineering: {full_df.shape}")

    return full_df


# -----------------------
# 9. Helper Functions
# -----------------------
def suitability_class(prob):
    if prob >= 0.75:
        return "Highly suitable"
    elif prob >= 0.50:
        return "Suitable"
    elif prob >= 0.30:
        return "Moderately suitable"
    else:
        return "Low / not suitable"


def find_species(name_part):
    matches = [sp for sp in le.classes_ if name_part.lower() in sp.lower()]

    if not matches:
        print("No species found.")
    else:
        for sp in matches:
            print(sp)


# ============================================================
# MAIN PIPELINE
# ============================================================

# -----------------------
# 10. Load Data
# -----------------------
gbif = load_gbif_txt(GBIF_PATH)
gbif.to_csv(f"{SAVE_DIR}/clean_gbif.csv", index=False)

species_counts = gbif["species"].value_counts().reset_index()
species_counts.columns = ["species", "records"]
species_counts.to_csv(f"{SAVE_DIR}/species_counts.csv", index=False)


# -----------------------
# 11. Init Extractor
# -----------------------
extractor = EnvironmentalExtractor(
    climate_folder=CLIMATE_DIR,
    elevation_path=ELEVATION_PATH
)


# -----------------------
# 12. Build Dataset
# -----------------------
dataset = build_dataset(gbif, extractor)

logging.info(f"Final dataset shape: {dataset.shape}")
logging.info(f"Class distribution:\n{dataset['label'].value_counts()}")
logging.info(f"Missing values total: {dataset.isna().sum().sum()}")

dataset.to_csv(f"{SAVE_DIR}/catboost_phyto_dataset.csv", index=False)
dataset.to_parquet(f"{SAVE_DIR}/catboost_phyto_dataset.parquet", index=False)


# -----------------------
# 13. Split
# -----------------------
X = dataset.drop(columns=["label"])
y = dataset["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

logging.info(f"Train size: {X_train.shape}")
logging.info(f"Test size: {X_test.shape}")


# -----------------------
# 14. Prepare Features for CatBoost
# -----------------------
X_train = X_train.copy()
X_test = X_test.copy()

# Keep diagnostics
X_train[["species", "lat", "lon"]].to_csv(f"{SAVE_DIR}/train_diagnostics.csv", index=False)
X_test[["species", "lat", "lon"]].to_csv(f"{SAVE_DIR}/test_diagnostics.csv", index=False)

# Remove coordinates to avoid direct geographic memorization
X_train = X_train.drop(columns=["lat", "lon"])
X_test = X_test.drop(columns=["lat", "lon"])

# For CatBoost, keep species as categorical string
cat_features = ["species"]

feature_names = X_train.columns.tolist()

logging.info(f"Feature count: {len(feature_names)}")
logging.info(f"Categorical features: {cat_features}")


# -----------------------
# 15. Impute Numeric Features
# -----------------------
numeric_features = [col for col in feature_names if col not in cat_features]

imputer = SimpleImputer(strategy="median")

X_train[numeric_features] = imputer.fit_transform(X_train[numeric_features])
X_test[numeric_features] = imputer.transform(X_test[numeric_features])

logging.info(f"NaNs train: {X_train.isna().sum().sum()}")
logging.info(f"NaNs test: {X_test.isna().sum().sum()}")

X_train.to_csv(f"{SAVE_DIR}/X_train_catboost_processed.csv", index=False)
X_test.to_csv(f"{SAVE_DIR}/X_test_catboost_processed.csv", index=False)
y_train.to_csv(f"{SAVE_DIR}/y_train.csv", index=False)
y_test.to_csv(f"{SAVE_DIR}/y_test.csv", index=False)


# -----------------------
# 16. Train CatBoost
# -----------------------
cat_model = CatBoostClassifier(
    iterations=1500,
    learning_rate=0.025,
    depth=8,
    loss_function="Logloss",
    eval_metric="AUC",
    random_seed=42,
    l2_leaf_reg=3,
    subsample=0.9,
    bootstrap_type="Bernoulli",
    verbose=100
)

logging.info("Training CatBoost model...")

cat_model.fit(
    X_train,
    y_train,
    cat_features=cat_features,
    eval_set=(X_test, y_test),
    use_best_model=True
)

logging.info("CatBoost training completed ✅")


# -----------------------
# 17. Save Model + Artifacts
# -----------------------
cat_model.save_model(f"{SAVE_DIR}/catboost_phyto_model.cbm")
joblib.dump(cat_model, f"{SAVE_DIR}/catboost_phyto_model.pkl")
joblib.dump(imputer, f"{SAVE_DIR}/numeric_imputer.pkl")
joblib.dump(feature_names, f"{SAVE_DIR}/feature_names.pkl")
joblib.dump(cat_features, f"{SAVE_DIR}/cat_features.pkl")
joblib.dump(numeric_features, f"{SAVE_DIR}/numeric_features.pkl")

logging.info("CatBoost model + artifacts saved ✅")


# -----------------------
# 18. Evaluate
# -----------------------
y_pred = cat_model.predict(X_test)
y_prob = cat_model.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
report = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

logging.info(f"CatBoost Accuracy: {acc:.4f}")
logging.info(f"CatBoost AUC: {auc:.4f}")

print("\nClassification Report:\n")
print(report)

print("\nConfusion Matrix:")
print(cm)

with open(f"{SAVE_DIR}/catboost_evaluation_report.txt", "w") as f:
    f.write(f"CatBoost Accuracy: {acc:.4f}\n")
    f.write(f"CatBoost AUC: {auc:.4f}\n\n")
    f.write("Classification Report:\n")
    f.write(report)
    f.write("\nConfusion Matrix:\n")
    f.write(str(cm))


# -----------------------
# 19. Feature Importance
# -----------------------
importance_values = cat_model.get_feature_importance()

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importance_values
}).sort_values("importance", ascending=False)

importance_df.to_csv(f"{SAVE_DIR}/catboost_feature_importance.csv", index=False)

print("\nTop 15 CatBoost Features:")
print(importance_df.head(15))


# -----------------------
# 20. Prediction Function
# -----------------------
def predict_species_suitability_catboost(city_name, lat, lon, species_name):
    if species_name not in gbif["species"].unique():
        print(f"'{species_name}' not found.")
        print("Closest matches:")
        for sp in sorted(gbif["species"].unique()):
            if species_name.split()[0].lower() in sp.lower():
                print("-", sp)
        return None

    env_values = extractor.extract_point(lat, lon)

    base_cols = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

    sample_df = pd.DataFrame([env_values], columns=base_cols)
    sample_df = add_engineered_features(sample_df)

    sample_df["species"] = species_name

    # Match training columns
    sample_df = sample_df[feature_names]

    sample_df[numeric_features] = imputer.transform(sample_df[numeric_features])

    prob = cat_model.predict_proba(sample_df)[0][1]
    label = int(prob >= 0.5)

    print("====================================")
    print(f"City: {city_name}")
    print(f"Species: {species_name}")
    print(f"Suitability Probability: {prob:.4f}")
    print(f"Suitability Class: {suitability_class(prob)}")
    print(f"Binary Prediction: {'Suitable' if label == 1 else 'Not suitable'}")
    print("====================================")

    return float(prob), label


# -----------------------
# 21. Batch Prediction
# -----------------------
def batch_predict_catboost(cities, species_list):
    results = []

    for city_name, lat, lon in cities:
        for species_name in species_list:
            output = predict_species_suitability_catboost(
                city_name,
                lat,
                lon,
                species_name
            )

            if output is None:
                continue

            prob, label = output

            results.append({
                "city": city_name,
                "lat": lat,
                "lon": lon,
                "species": species_name,
                "probability": prob,
                "class": suitability_class(prob),
                "binary_label": label
            })

    results_df = pd.DataFrame(results)
    results_df.to_csv(f"{SAVE_DIR}/catboost_city_species_predictions.csv", index=False)

    return results_df


# -----------------------
# 22. Test Cities and Species
# -----------------------
test_cities = [
    ("Beirut", 33.8938, 35.5018),
    ("Tripoli", 34.4367, 35.8497),
    ("Byblos", 34.1230, 35.6519),
    ("Bcharre", 34.2508, 36.0106),
    ("Cedars of God", 34.2436, 36.0486),
    ("Faraya", 33.9944, 35.8172),
    ("Zahle", 33.8463, 35.9020),
    ("Baalbek", 34.0060, 36.2181),
    ("Sidon", 33.5630, 35.3688),
    ("Tyre", 33.2700, 35.2038)
]

test_species = [
    "Cedrus libani",
    "Ceratonia siliqua",
    "Abies cilicica",
    "Quercus coccifera calliprinos",
    "Quercus infectoria boissieri",
    "Arbutus andrachne",
    "Juniperus excelsa",
    "Juniperus drupacea"
]

predictions_df = batch_predict_catboost(test_cities, test_species)

print("\nPrediction summary:")
print(predictions_df.sort_values("probability", ascending=False).head(20))

logging.info("CatBoost pipeline completed successfully 🚀")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.3 MB/s eta 0:00:00
2026-05-10 06:40:48,214 - INFO - Logging is working ✅
2026-05-10 06:40:48,222 - INFO - Saving outputs to: /content/drive/MyDrive/PhytoLB/model_catboost_v1
2026-05-10 06:40:48,292 - INFO - GBIF loaded: 13748 records
2026-05-10 06:40:48,294 - INFO - Unique species: 27
2026-05-10 06:40:48,438 - INFO - Climate + elevation rasters loaded ✅
2026-05-10 06:40:48,443 - INFO - Extracting presence features...
2026-05-10 06:40:48,459 - INFO - Processed 0/13748 points
2026-05-10 06:40:51,245 - INFO - Processed 1000/13748 points
2026-05-10 06:40:55,226 - INFO - Processed 2000/13748 points
2026-05-10 06:40:58,130 - INFO - Processed 3000/13748 points
2026-05-10 06:41:00,975 - INFO - Processed 4000/13748 points
2026-05-10 06:41:03,756 - INFO - Processed 5000/13748 points
2026-05-10 06:41:06,920 - INFO - Processed 6000/13748 points
2026-05-10 06:41:10,823 - INFO - Processed 7000/13748 points
2026-05-10 06:41:13,483 - INFO - Processed 8000/13748 points
2026-05-10 06:41:16,286 - INFO - Processed 9000/13748 points
2026-05-10 06:41:19,036 - INFO - Processed 10000/13748 points
2026-05-10 06:41:22,914 - INFO - Processed 11000/13748 points
2026-05-10 06:41:26,222 - INFO - Processed 12000/13748 points
2026-05-10 06:41:29,029 - INFO - Processed 13000/13748 points
2026-05-10 06:41:31,131 - INFO - Generating filtered pseudo-absence points...
2026-05-10 06:41:36,400 - INFO - Generated 1000/13748 valid pseudo-absences
2026-05-10 06:41:41,546 - INFO - Generated 2000/13748 valid pseudo-absences
2026-05-10 06:41:45,903 - INFO - Generated 3000/13748 valid pseudo-absences
2026-05-10 06:41:50,918 - INFO - Generated 4000/13748 valid pseudo-absences
2026-05-10 06:41:56,051 - INFO - Generated 5000/13748 valid pseudo-absences
2026-05-10 06:42:00,570 - INFO - Generated 6000/13748 valid pseudo-absences
2026-05-10 06:42:06,289 - INFO - Generated 7000/13748 valid pseudo-absences
2026-05-10 06:42:11,191 - INFO - Generated 8000/13748 valid pseudo-absences
2026-05-10 06:42:15,528 - INFO - Generated 9000/13748 valid pseudo-absences
2026-05-10 06:42:21,312 - INFO - Generated 10000/13748 valid pseudo-absences
2026-05-10 06:42:26,028 - INFO - Generated 11000/13748 valid pseudo-absences
2026-05-10 06:42:30,533 - INFO - Generated 12000/13748 valid pseudo-absences
2026-05-10 06:42:36,497 - INFO - Generated 13000/13748 valid pseudo-absences
2026-05-10 06:42:39,867 - INFO - Extracting pseudo-absence features...
2026-05-10 06:42:39,873 - INFO - Processed 0/13748 points
2026-05-10 06:42:42,676 - INFO - Processed 1000/13748 points
2026-05-10 06:42:45,480 - INFO - Processed 2000/13748 points
2026-05-10 06:42:49,306 - INFO - Processed 3000/13748 points
2026-05-10 06:42:52,540 - INFO - Processed 4000/13748 points
2026-05-10 06:42:55,257 - INFO - Processed 5000/13748 points
2026-05-10 06:42:58,048 - INFO - Processed 6000/13748 points
2026-05-10 06:43:01,059 - INFO - Processed 7000/13748 points
2026-05-10 06:43:05,171 - INFO - Processed 8000/13748 points
2026-05-10 06:43:07,905 - INFO - Processed 9000/13748 points
2026-05-10 06:43:10,725 - INFO - Processed 10000/13748 points
2026-05-10 06:43:13,492 - INFO - Processed 11000/13748 points
2026-05-10 06:43:17,069 - INFO - Processed 12000/13748 points
2026-05-10 06:43:20,657 - INFO - Processed 13000/13748 points
2026-05-10 06:43:22,815 - INFO - Dataset before filtering: (27496, 24)
2026-05-10 06:43:22,824 - INFO - Dataset after feature engineering: (27496, 32)
2026-05-10 06:43:22,826 - INFO - Final dataset shape: (27496, 32)
2026-05-10 06:43:22,828 - INFO - Class distribution:
label
1    13748
0    13748
Name: count, dtype: int64
2026-05-10 06:43:22,833 - INFO - Missing values total: 0
2026-05-10 06:43:23,716 - INFO - Train size: (21996, 31)
2026-05-10 06:43:23,718 - INFO - Test size: (5500, 31)
2026-05-10 06:43:23,850 - INFO - Feature count: 29
2026-05-10 06:43:23,851 - INFO - Categorical features: ['species']
2026-05-10 06:43:23,909 - INFO - NaNs train: 0
2026-05-10 06:43:23,913 - INFO - NaNs test: 0
2026-05-10 06:43:24,676 - INFO - Training CatBoost model...
0:	test: 0.8818348	best: 0.8818348 (0)	total: 87.2ms	remaining: 2m 10s
100:	test: 0.9537927	best: 0.9537927 (100)	total: 3.97s	remaining: 55s
200:	test: 0.9597780	best: 0.9597780 (200)	total: 9.34s	remaining: 1m
300:	test: 0.9619632	best: 0.9619632 (300)	total: 13.1s	remaining: 52.3s
400:	test: 0.9633295	best: 0.9633295 (400)	total: 17s	remaining: 46.7s
500:	test: 0.9640578	best: 0.9640578 (500)	total: 21.9s	remaining: 43.8s
600:	test: 0.9644361	best: 0.9644361 (600)	total: 26s	remaining: 38.9s
700:	test: 0.9645931	best: 0.9646580 (673)	total: 29.7s	remaining: 33.9s
800:	test: 0.9647995	best: 0.9647995 (800)	total: 33.9s	remaining: 29.6s
900:	test: 0.9648587	best: 0.9649154 (861)	total: 38.9s	remaining: 25.8s
1000:	test: 0.9649998	best: 0.9650255 (972)	total: 42.7s	remaining: 21.3s
1100:	test: 0.9650787	best: 0.9650892 (1092)	total: 46.4s	remaining: 16.8s
1200:	test: 0.9650610	best: 0.9651187 (1146)	total: 51.6s	remaining: 12.8s
1300:	test: 0.9650233	best: 0.9651332 (1259)	total: 55.4s	remaining: 8.47s
1400:	test: 0.9649367	best: 0.9651332 (1259)	total: 59.2s	remaining: 4.18s
1499:	test: 0.9648458	best: 0.9651332 (1259)	total: 1m 3s	remaining: 0us

bestTest = 0.9651332231
bestIteration = 1259

Shrink model to first 1260 iterations.
2026-05-10 06:44:29,021 - INFO - CatBoost training completed ✅
2026-05-10 06:44:29,143 - INFO - CatBoost model + artifacts saved ✅
2026-05-10 06:44:29,319 - INFO - CatBoost Accuracy: 0.9185
2026-05-10 06:44:29,320 - INFO - CatBoost AUC: 0.9651

Classification Report:

              precision    recall  f1-score   support

           0       0.96      0.88      0.92      2750
           1       0.89      0.96      0.92      2750

    accuracy                           0.92      5500
   macro avg       0.92      0.92      0.92      5500
weighted avg       0.92      0.92      0.92      5500


Confusion Matrix:
[[2415  335]
 [ 113 2637]]

Top 15 CatBoost Features:
                         feature  importance
20                       species   18.516254
28  elevation_precip_interaction   11.826178
27    elevation_temp_interaction   11.425840
19                     elevation   10.856956
26    summer_winter_precip_ratio    4.746655
11                         BIO12    3.781023
14                         BIO15    3.483139
16                         BIO17    2.867659
4                           BIO5    2.583450
18                         BIO19    2.375358
25                 dryness_ratio    2.288227
21             temp_annual_range    2.181962
2                           BIO3    2.053030
9                          BIO10    1.835054
1                           BIO2    1.737730
====================================
City: Beirut
Species: Cedrus libani
Suitability Probability: 0.0014
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Ceratonia siliqua
Suitability Probability: 0.7899
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Beirut
Species: Abies cilicica
Suitability Probability: 0.0011
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Quercus coccifera calliprinos
Suitability Probability: 0.5644
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Beirut
Species: Quercus infectoria boissieri
Suitability Probability: 0.1229
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Arbutus andrachne
Suitability Probability: 0.6281
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Beirut
Species: Juniperus excelsa
Suitability Probability: 0.0006
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Beirut
Species: Juniperus drupacea
Suitability Probability: 0.0038
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Cedrus libani
Suitability Probability: 0.0018
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Ceratonia siliqua
Suitability Probability: 0.7259
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Tripoli
Species: Abies cilicica
Suitability Probability: 0.0046
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0797
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Quercus infectoria boissieri
Suitability Probability: 0.0178
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Arbutus andrachne
Suitability Probability: 0.3210
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Juniperus excelsa
Suitability Probability: 0.0014
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Tripoli
Species: Juniperus drupacea
Suitability Probability: 0.0019
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Cedrus libani
Suitability Probability: 0.0065
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Ceratonia siliqua
Suitability Probability: 0.9262
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Byblos
Species: Abies cilicica
Suitability Probability: 0.0074
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Quercus coccifera calliprinos
Suitability Probability: 0.7977
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Byblos
Species: Quercus infectoria boissieri
Suitability Probability: 0.1017
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Arbutus andrachne
Suitability Probability: 0.7176
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Byblos
Species: Juniperus excelsa
Suitability Probability: 0.0047
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Byblos
Species: Juniperus drupacea
Suitability Probability: 0.0147
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Cedrus libani
Suitability Probability: 0.5512
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Ceratonia siliqua
Suitability Probability: 0.0715
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Abies cilicica
Suitability Probability: 0.6605
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Quercus coccifera calliprinos
Suitability Probability: 0.7798
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Quercus infectoria boissieri
Suitability Probability: 0.8358
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Arbutus andrachne
Suitability Probability: 0.3170
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Bcharre
Species: Juniperus excelsa
Suitability Probability: 0.9304
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Bcharre
Species: Juniperus drupacea
Suitability Probability: 0.4180
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Cedrus libani
Suitability Probability: 0.5410
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Cedars of God
Species: Ceratonia siliqua
Suitability Probability: 0.0026
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Abies cilicica
Suitability Probability: 0.3717
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0213
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Quercus infectoria boissieri
Suitability Probability: 0.0574
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Arbutus andrachne
Suitability Probability: 0.0160
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Cedars of God
Species: Juniperus excelsa
Suitability Probability: 0.8721
Suitability Class: Highly suitable
Binary Prediction: Suitable
====================================
====================================
City: Cedars of God
Species: Juniperus drupacea
Suitability Probability: 0.0422
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Cedrus libani
Suitability Probability: 0.3292
Suitability Class: Moderately suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Ceratonia siliqua
Suitability Probability: 0.0020
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Abies cilicica
Suitability Probability: 0.0344
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Quercus coccifera calliprinos
Suitability Probability: 0.1207
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Quercus infectoria boissieri
Suitability Probability: 0.6080
Suitability Class: Suitable
Binary Prediction: Suitable
====================================
====================================
City: Faraya
Species: Arbutus andrachne
Suitability Probability: 0.0254
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Juniperus excelsa
Suitability Probability: 0.0994
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Faraya
Species: Juniperus drupacea
Suitability Probability: 0.0966
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Cedrus libani
Suitability Probability: 0.0026
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Ceratonia siliqua
Suitability Probability: 0.0053
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Abies cilicica
Suitability Probability: 0.0035
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Quercus coccifera calliprinos
Suitability Probability: 0.0892
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Quercus infectoria boissieri
Suitability Probability: 0.0937
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Arbutus andrachne
Suitability Probability: 0.0218
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Juniperus excelsa
Suitability Probability: 0.0261
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Zahle
Species: Juniperus drupacea
Suitability Probability: 0.0035
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Cedrus libani
Suitability Probability: 0.0063
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Ceratonia siliqua
Suitability Probability: 0.0026
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Abies cilicica
Suitability Probability: 0.0112
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Quercus coccifera calliprinos
Suitability Probability: 0.2458
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================
City: Baalbek
Species: Quercus infectoria boissieri
Suitability Probability: 0.0827
Suitability Class: Low / not suitable
Binary Prediction: Not suitable
====================================
====================================

# Testing 4 models

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install catboost -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.1 MB/s eta 0:00:00

In [ ]:
# ============================================================
# Compare Saved PhytoLB Models
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd
import rasterio

from catboost import CatBoostClassifier

# -----------------------
# 1. Paths
# -----------------------
BASE_DIR = "/content/drive/MyDrive/PhytoLB"

MODEL_DIRS = {
    "CatBoost_v1": f"{BASE_DIR}/model_catboost_v1",
    "LightGBM_v5": f"{BASE_DIR}/model_enhanced_v5_BETTER_IN_LAT_LONG_acc92_auc_96",
    "LightGBM_v4": f"{BASE_DIR}/model_enhanced_v4_BEST_IN_PREDICTION_acc92_auc_96",
    "LightGBM_v3": f"{BASE_DIR}/model_enhanced_v3_acc93_auc97",
}

CLIMATE_DIR = f"{BASE_DIR}/wc2.1_10m_bio"
ELEVATION_PATH = f"{BASE_DIR}/elevation/elevation.tif"


# -----------------------
# 2. Environmental Extractor
# -----------------------
class EnvironmentalExtractor:
    def __init__(self, climate_folder, elevation_path):
        self.climate_rasters = []

        for i in range(1, 20):
            path = os.path.join(climate_folder, f"wc2.1_10m_bio_{i}.tif")
            self.climate_rasters.append(rasterio.open(path))

        self.elevation_raster = rasterio.open(elevation_path)

    def extract_point(self, lat, lon):
        values = []

        for raster in self.climate_rasters:
            try:
                val = next(raster.sample([(lon, lat)]))[0]
                if raster.nodata is not None and val == raster.nodata:
                    val = np.nan
            except:
                val = np.nan

            values.append(val)

        try:
            elev = next(self.elevation_raster.sample([(lon, lat)]))[0]
            if self.elevation_raster.nodata is not None and elev == self.elevation_raster.nodata:
                elev = np.nan
        except:
            elev = np.nan

        values.append(elev)

        return values


extractor = EnvironmentalExtractor(CLIMATE_DIR, ELEVATION_PATH)


# -----------------------
# 3. Feature Engineering
# -----------------------
def add_engineered_features(df):
    df = df.copy()

    if "elevation" in df.columns:
        df["temp_annual_range"] = df["BIO5"] - df["BIO6"]
        df["warm_cold_quarter_diff"] = df["BIO10"] - df["BIO11"]

        df["precip_wet_dry_month_diff"] = df["BIO13"] - df["BIO14"]
        df["precip_wet_dry_quarter_diff"] = df["BIO16"] - df["BIO17"]

        df["dryness_ratio"] = df["BIO17"] / (df["BIO16"] + 1e-6)
        df["summer_winter_precip_ratio"] = df["BIO18"] / (df["BIO19"] + 1e-6)

        df["elevation_temp_interaction"] = df["elevation"] * df["BIO1"]
        df["elevation_precip_interaction"] = df["elevation"] * df["BIO12"]

    return df


def suitability_class(prob):
    if prob >= 0.75:
        return "Highly suitable"
    elif prob >= 0.50:
        return "Suitable"
    elif prob >= 0.30:
        return "Moderately suitable"
    else:
        return "Low / not suitable"


# -----------------------
# 4. Load Models
# -----------------------
def load_model_bundle(model_name, model_dir):
    bundle = {"name": model_name, "dir": model_dir}

    if model_name.startswith("CatBoost"):
        model_path = f"{model_dir}/catboost_phyto_model.cbm"

        model = CatBoostClassifier()
        model.load_model(model_path)

        bundle["type"] = "catboost"
        bundle["model"] = model
        bundle["imputer"] = joblib.load(f"{model_dir}/numeric_imputer.pkl")
        bundle["feature_names"] = joblib.load(f"{model_dir}/feature_names.pkl")
        bundle["numeric_features"] = joblib.load(f"{model_dir}/numeric_features.pkl")
        bundle["cat_features"] = joblib.load(f"{model_dir}/cat_features.pkl")

    else:
        bundle["type"] = "lightgbm"
        bundle["model"] = joblib.load(f"{model_dir}/phyto_lightgbm_model.pkl")
        bundle["encoder"] = joblib.load(f"{model_dir}/species_encoder.pkl")
        bundle["imputer"] = joblib.load(f"{model_dir}/imputer.pkl")
        bundle["feature_names"] = joblib.load(f"{model_dir}/feature_names.pkl")

    return bundle


models = []

for name, path in MODEL_DIRS.items():
    print("Loading:", name)
    models.append(load_model_bundle(name, path))

print("Loaded models:", [m["name"] for m in models])


# -----------------------
# 5. Predict With One Model
# -----------------------
def predict_with_model(bundle, city_name, lat, lon, species_name):
    env_values = extractor.extract_point(lat, lon)

    # Base environmental columns
    base_cols = [f"BIO{i}" for i in range(1, 20)] + ["elevation"]

    sample = pd.DataFrame([env_values], columns=base_cols)
    sample = add_engineered_features(sample)

    if bundle["type"] == "catboost":
        sample["species"] = species_name

        # Match CatBoost training columns
        sample = sample[bundle["feature_names"]]

        # Impute numeric only
        sample[bundle["numeric_features"]] = bundle["imputer"].transform(
            sample[bundle["numeric_features"]]
        )

        prob = bundle["model"].predict_proba(sample)[0][1]

    else:
        encoder = bundle["encoder"]

        if species_name not in encoder.classes_:
            return None

        sample["species_id"] = encoder.transform([species_name])[0]

        # Match LightGBM model features
        sample = sample[bundle["feature_names"]]

        sample = pd.DataFrame(
            bundle["imputer"].transform(sample),
            columns=bundle["feature_names"]
        )

        prob = bundle["model"].predict_proba(sample)[0][1]

    return float(prob)


# -----------------------
# 6. Test Samples
# -----------------------
test_samples = [
    ("Beirut", 33.8938, 35.5018, "Cedrus libani"),
    ("Cedars of God", 34.2436, 36.0486, "Cedrus libani"),
    ("Bcharre", 34.2508, 36.0106, "Cedrus libani"),
    ("Byblos", 34.1230, 35.6519, "Ceratonia siliqua"),
    ("Beirut", 33.8938, 35.5018, "Ceratonia siliqua"),
    ("Faraya", 33.9944, 35.8172, "Ceratonia siliqua"),
    ("Cedars of God", 34.2436, 36.0486, "Abies cilicica"),
    ("Faraya", 33.9944, 35.8172, "Abies cilicica"),
    ("Bcharre", 34.2508, 36.0106, "Juniperus excelsa"),
    ("Tyre", 33.2700, 35.2038, "Cedrus libani"),
    ("Byblos", 34.1230, 35.6519, "Quercus coccifera calliprinos"),
    ("Bcharre", 34.2508, 36.0106, "Quercus infectoria boissieri"),
]


# -----------------------
# 7. Compare Models
# -----------------------
results = []

for city, lat, lon, species in test_samples:
    row = {
        "city": city,
        "species": species,
        "lat": lat,
        "lon": lon,
    }

    for bundle in models:
        prob = predict_with_model(bundle, city, lat, lon, species)

        if prob is None:
            row[bundle["name"]] = np.nan
        else:
            row[bundle["name"]] = prob

    results.append(row)


comparison_df = pd.DataFrame(results)

# Add best model per sample
model_cols = list(MODEL_DIRS.keys())

comparison_df["best_model"] = comparison_df[model_cols].idxmax(axis=1)
comparison_df["best_probability"] = comparison_df[model_cols].max(axis=1)
comparison_df["best_class"] = comparison_df["best_probability"].apply(suitability_class)

comparison_df

Loading: CatBoost_v1
Loading: LightGBM_v5
Loading: LightGBM_v4
Loading: LightGBM_v3
Loaded models: ['CatBoost_v1', 'LightGBM_v5', 'LightGBM_v4', 'LightGBM_v3']

,city,species,lat,lon,CatBoost_v1,LightGBM_v5,LightGBM_v4,LightGBM_v3,best_model,best_probability,best_class
0,Beirut,Cedrus libani,33.8938,35.5018,0.001366,0.015594,0.034200,0.059734,LightGBM_v3,0.059734,Low / not suitable
1,Cedars of God,Cedrus libani,34.2436,36.0486,0.540965,0.674516,0.721625,0.586523,LightGBM_v4,0.721625,Suitable
2,Bcharre,Cedrus libani,34.2508,36.0106,0.551180,0.532650,0.566162,0.674556,LightGBM_v3,0.674556,Suitable
3,Byblos,Ceratonia siliqua,34.1230,35.6519,0.926218,0.950904,0.918992,0.985767,LightGBM_v3,0.985767,Highly suitable
4,Beirut,Ceratonia siliqua,33.8938,35.5018,0.789922,0.712382,0.800888,0.832810,LightGBM_v3,0.832810,Highly suitable
5,Faraya,Ceratonia siliqua,33.9944,35.8172,0.002020,0.021000,0.014283,0.024090,LightGBM_v3,0.024090,Low / not suitable
6,Cedars of God,Abies cilicica,34.2436,36.0486,0.371673,0.707631,0.738559,0.527037,LightGBM_v4,0.738559,Suitable
7,Faraya,Abies cilicica,33.9944,35.8172,0.034441,0.014304,0.015813,0.008149,CatBoost_v1,0.034441,Low / not suitable
8,Bcharre,Juniperus excelsa,34.2508,36.0106,0.930415,0.954444,0.970405,0.931928,LightGBM_v4,0.970405,Highly suitable
9,Tyre,Cedrus libani,33.2700,35.2038,0.000120,0.000922,0.000595,0.000640,LightGBM_v5,0.000922,Low / not suitable
10,Byblos,Quercus coccifera calliprinos,34.1230,35.6519,0.797653,0.908576,0.850123,0.847888,LightGBM_v5,0.908576,Highly suitable
11,Bcharre,Quercus infectoria boissieri,34.2508,36.0106,0.835806,0.881883,0.892650,0.705991,LightGBM_v4,0.892650,Highly suitable

In [ ]:
output_path = f"{BASE_DIR}/model_comparison_samples.csv"
comparison_df.to_csv(output_path, index=False)

print("Saved comparison to:", output_path)

Saved comparison to: /content/drive/MyDrive/PhytoLB/model_comparison_samples.csv

In [ ]:
comparison_df[
    ["city", "species"] + list(MODEL_DIRS.keys()) + ["best_model", "best_class"]
]

,city,species,CatBoost_v1,LightGBM_v5,LightGBM_v4,LightGBM_v3,best_model,best_class
0,Beirut,Cedrus libani,0.001366,0.015594,0.034200,0.059734,LightGBM_v3,Low / not suitable
1,Cedars of God,Cedrus libani,0.540965,0.674516,0.721625,0.586523,LightGBM_v4,Suitable
2,Bcharre,Cedrus libani,0.551180,0.532650,0.566162,0.674556,LightGBM_v3,Suitable
3,Byblos,Ceratonia siliqua,0.926218,0.950904,0.918992,0.985767,LightGBM_v3,Highly suitable
4,Beirut,Ceratonia siliqua,0.789922,0.712382,0.800888,0.832810,LightGBM_v3,Highly suitable
5,Faraya,Ceratonia siliqua,0.002020,0.021000,0.014283,0.024090,LightGBM_v3,Low / not suitable
6,Cedars of God,Abies cilicica,0.371673,0.707631,0.738559,0.527037,LightGBM_v4,Suitable
7,Faraya,Abies cilicica,0.034441,0.014304,0.015813,0.008149,CatBoost_v1,Low / not suitable
8,Bcharre,Juniperus excelsa,0.930415,0.954444,0.970405,0.931928,LightGBM_v4,Highly suitable
9,Tyre,Cedrus libani,0.000120,0.000922,0.000595,0.000640,LightGBM_v5,Low / not suitable
10,Byblos,Quercus coccifera calliprinos,0.797653,0.908576,0.850123,0.847888,LightGBM_v5,Highly suitable
11,Bcharre,Quercus infectoria boissieri,0.835806,0.881883,0.892650,0.705991,LightGBM_v4,Highly suitable